apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "es-ch-sync.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/stream/es/host
    secretKey: ELASTICSEARCH_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/stream/es/user
    secretKey: ELASTICSEARCH_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/stream/es/pass
    secretKey: ELASTICSEARCH_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/stream/clickhouse/host
    secretKey: CLICKHOUSE_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/stream/clickhouse/user
    secretKey: CLICKHOUSE_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/stream/clickhouse/pass
    secretKey: CLICKHOUSE_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "es-ch-sync.fullname" . }}-secret
    template:
      metadata: {}
